/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BusinessesRouteImport } from './routes/businesses'
import { Route as FaqsRouteImport } from './routes/faqs'
import { Route as FarmerPartnershipRouteImport } from './routes/farmer-partnership'
import { Route as FeedsRouteImport } from './routes/feeds'
import { Route as GeneticsHatcheryRouteImport } from './routes/genetics-hatchery'
import { Route as ImpactRouteImport } from './routes/impact'
import { Route as PoultryRouteImport } from './routes/poultry'
import { Route as FieldNotesIndexRouteImport } from './routes/field-notes.index'
import { Route as FieldNotesSlugRouteImport } from './routes/field-notes.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessesRoute = BusinessesRouteImport.update({
  id: '/businesses',
  path: '/businesses',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqsRoute = FaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerPartnershipRoute = FarmerPartnershipRouteImport.update({
  id: '/farmer-partnership',
  path: '/farmer-partnership',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedsRoute = FeedsRouteImport.update({
  id: '/feeds',
  path: '/feeds',
  getParentRoute: () => rootRouteImport,
} as any)
const GeneticsHatcheryRoute = GeneticsHatcheryRouteImport.update({
  id: '/genetics-hatchery',
  path: '/genetics-hatchery',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactRoute = ImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => rootRouteImport,
} as any)
const PoultryRoute = PoultryRouteImport.update({
  id: '/poultry',
  path: '/poultry',
  getParentRoute: () => rootRouteImport,
} as any)
const FieldNotesIndexRoute = FieldNotesIndexRouteImport.update({
  id: '/field-notes/',
  path: '/field-notes/',
  getParentRoute: () => rootRouteImport,
} as any)
const FieldNotesSlugRoute = FieldNotesSlugRouteImport.update({
  id: '/field-notes/$slug',
  path: '/field-notes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/businesses': typeof BusinessesRoute
  '/faqs': typeof FaqsRoute
  '/farmer-partnership': typeof FarmerPartnershipRoute
  '/feeds': typeof FeedsRoute
  '/genetics-hatchery': typeof GeneticsHatcheryRoute
  '/impact': typeof ImpactRoute
  '/poultry': typeof PoultryRoute
  '/field-notes/$slug': typeof FieldNotesSlugRoute
  '/field-notes/': typeof FieldNotesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/businesses': typeof BusinessesRoute
  '/faqs': typeof FaqsRoute
  '/farmer-partnership': typeof FarmerPartnershipRoute
  '/feeds': typeof FeedsRoute
  '/genetics-hatchery': typeof GeneticsHatcheryRoute
  '/impact': typeof ImpactRoute
  '/poultry': typeof PoultryRoute
  '/field-notes/$slug': typeof FieldNotesSlugRoute
  '/field-notes': typeof FieldNotesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/businesses': typeof BusinessesRoute
  '/faqs': typeof FaqsRoute
  '/farmer-partnership': typeof FarmerPartnershipRoute
  '/feeds': typeof FeedsRoute
  '/genetics-hatchery': typeof GeneticsHatcheryRoute
  '/impact': typeof ImpactRoute
  '/poultry': typeof PoultryRoute
  '/field-notes/$slug': typeof FieldNotesSlugRoute
  '/field-notes/': typeof FieldNotesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/businesses'
    | '/faqs'
    | '/farmer-partnership'
    | '/feeds'
    | '/genetics-hatchery'
    | '/impact'
    | '/poultry'
    | '/field-notes/$slug'
    | '/field-notes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/businesses'
    | '/faqs'
    | '/farmer-partnership'
    | '/feeds'
    | '/genetics-hatchery'
    | '/impact'
    | '/poultry'
    | '/field-notes/$slug'
    | '/field-notes'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/businesses'
    | '/faqs'
    | '/farmer-partnership'
    | '/feeds'
    | '/genetics-hatchery'
    | '/impact'
    | '/poultry'
    | '/field-notes/$slug'
    | '/field-notes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BusinessesRoute: typeof BusinessesRoute
  FaqsRoute: typeof FaqsRoute
  FarmerPartnershipRoute: typeof FarmerPartnershipRoute
  FeedsRoute: typeof FeedsRoute
  GeneticsHatcheryRoute: typeof GeneticsHatcheryRoute
  ImpactRoute: typeof ImpactRoute
  PoultryRoute: typeof PoultryRoute
  FieldNotesSlugRoute: typeof FieldNotesSlugRoute
  FieldNotesIndexRoute: typeof FieldNotesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/businesses': {
      id: '/businesses'
      path: '/businesses'
      fullPath: '/businesses'
      preLoaderRoute: typeof BusinessesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faqs': {
      id: '/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof FaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer-partnership': {
      id: '/farmer-partnership'
      path: '/farmer-partnership'
      fullPath: '/farmer-partnership'
      preLoaderRoute: typeof FarmerPartnershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feeds': {
      id: '/feeds'
      path: '/feeds'
      fullPath: '/feeds'
      preLoaderRoute: typeof FeedsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/genetics-hatchery': {
      id: '/genetics-hatchery'
      path: '/genetics-hatchery'
      fullPath: '/genetics-hatchery'
      preLoaderRoute: typeof GeneticsHatcheryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impact': {
      id: '/impact'
      path: '/impact'
      fullPath: '/impact'
      preLoaderRoute: typeof ImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poultry': {
      id: '/poultry'
      path: '/poultry'
      fullPath: '/poultry'
      preLoaderRoute: typeof PoultryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/field-notes/': {
      id: '/field-notes/'
      path: '/field-notes'
      fullPath: '/field-notes/'
      preLoaderRoute: typeof FieldNotesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/field-notes/$slug': {
      id: '/field-notes/$slug'
      path: '/field-notes/$slug'
      fullPath: '/field-notes/$slug'
      preLoaderRoute: typeof FieldNotesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BusinessesRoute: BusinessesRoute,
  FaqsRoute: FaqsRoute,
  FarmerPartnershipRoute: FarmerPartnershipRoute,
  FeedsRoute: FeedsRoute,
  GeneticsHatcheryRoute: GeneticsHatcheryRoute,
  ImpactRoute: ImpactRoute,
  PoultryRoute: PoultryRoute,
  FieldNotesSlugRoute: FieldNotesSlugRoute,
  FieldNotesIndexRoute: FieldNotesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
